# coding: utf-8

"""
    (v2.0) Dynamics 365 Business Central

    (v2.0) Business Central Standard APIs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pybusinesscentral.api.sales_credit_memo_line_api import SalesCreditMemoLineApi


class TestSalesCreditMemoLineApi(unittest.TestCase):
    """SalesCreditMemoLineApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SalesCreditMemoLineApi()

    def tearDown(self) -> None:
        pass

    def test_delete_sales_credit_memo_line_for_sales_credit_memo(self) -> None:
        """Test case for delete_sales_credit_memo_line_for_sales_credit_memo

        Deletes an object of type salesCreditMemoLine in Dynamics 365 Business Central
        """
        pass

    def test_get_sales_credit_memo_line_for_sales_credit_memo(self) -> None:
        """Test case for get_sales_credit_memo_line_for_sales_credit_memo

        Retrieve the properties and relationships of an object of type salesCreditMemoLine for Dynamics 365 Business Central.
        """
        pass

    def test_list_sales_credit_memo_lines(self) -> None:
        """Test case for list_sales_credit_memo_lines

        Returns a list of salesCreditMemoLines
        """
        pass

    def test_list_sales_credit_memo_lines_for_sales_credit_memo(self) -> None:
        """Test case for list_sales_credit_memo_lines_for_sales_credit_memo

        Returns a list of salesCreditMemoLines
        """
        pass

    def test_patch_sales_credit_memo_line_for_sales_credit_memo(self) -> None:
        """Test case for patch_sales_credit_memo_line_for_sales_credit_memo

        Updates an object of type salesCreditMemoLine in Dynamics 365 Business Central
        """
        pass

    def test_post_sales_credit_memo_line(self) -> None:
        """Test case for post_sales_credit_memo_line

        Creates an object of type salesCreditMemoLine in Dynamics 365 Business Central
        """
        pass

    def test_post_sales_credit_memo_line_for_sales_credit_memo(self) -> None:
        """Test case for post_sales_credit_memo_line_for_sales_credit_memo

        Creates an object of type salesCreditMemoLine in Dynamics 365 Business Central
        """
        pass


if __name__ == '__main__':
    unittest.main()
