"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pybusinesscentral
from pybusinesscentral.api.dimension_line_api import DimensionLineApi  # noqa: E501


class TestDimensionLineApi(unittest.TestCase):
    """DimensionLineApi unit test stubs"""

    def setUp(self):
        self.api = DimensionLineApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_dimension_line(self):
        """Test case for delete_dimension_line

        Deletes an object of type dimensionLine in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_get_dimension_line(self):
        """Test case for get_dimension_line

        Retrieve the properties and relationships of an object of type dimensionLine for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_list_dimension_lines(self):
        """Test case for list_dimension_lines

        Returns a list of dimensionLines  # noqa: E501
        """
        pass

    def test_patch_dimension_line(self):
        """Test case for patch_dimension_line

        Updates an object of type dimensionLine in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_post_dimension_line(self):
        """Test case for post_dimension_line

        Creates an object of type dimensionLine in Dynamics 365 Business Central  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
