"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pybusinesscentral
from pybusinesscentral.api.picture_api import PictureApi  # noqa: E501


class TestPictureApi(unittest.TestCase):
    """PictureApi unit test stubs"""

    def setUp(self):
        self.api = PictureApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_picture(self):
        """Test case for delete_picture

        Deletes an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_delete_picture_for_customer(self):
        """Test case for delete_picture_for_customer

        Deletes an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_delete_picture_for_employee(self):
        """Test case for delete_picture_for_employee

        Deletes an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_delete_picture_for_item(self):
        """Test case for delete_picture_for_item

        Deletes an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_delete_picture_for_vendor(self):
        """Test case for delete_picture_for_vendor

        Deletes an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_get_picture(self):
        """Test case for get_picture

        Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_get_picture_for_customer(self):
        """Test case for get_picture_for_customer

        Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_get_picture_for_employee(self):
        """Test case for get_picture_for_employee

        Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_get_picture_for_item(self):
        """Test case for get_picture_for_item

        Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_get_picture_for_vendor(self):
        """Test case for get_picture_for_vendor

        Retrieve the properties and relationships of an object of type picture for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_list_picture(self):
        """Test case for list_picture

        Returns a list of picture  # noqa: E501
        """
        pass

    def test_list_picture_for_customer(self):
        """Test case for list_picture_for_customer

        Returns a list of picture  # noqa: E501
        """
        pass

    def test_list_picture_for_employee(self):
        """Test case for list_picture_for_employee

        Returns a list of picture  # noqa: E501
        """
        pass

    def test_list_picture_for_item(self):
        """Test case for list_picture_for_item

        Returns a list of picture  # noqa: E501
        """
        pass

    def test_list_picture_for_vendor(self):
        """Test case for list_picture_for_vendor

        Returns a list of picture  # noqa: E501
        """
        pass

    def test_patch_picture(self):
        """Test case for patch_picture

        Updates an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_patch_picture_for_customer(self):
        """Test case for patch_picture_for_customer

        Updates an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_patch_picture_for_employee(self):
        """Test case for patch_picture_for_employee

        Updates an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_patch_picture_for_item(self):
        """Test case for patch_picture_for_item

        Updates an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_patch_picture_for_vendor(self):
        """Test case for patch_picture_for_vendor

        Updates an object of type picture in Dynamics 365 Business Central  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
