"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pybusinesscentral
from pybusinesscentral.model.sales_credit_memo_line import SalesCreditMemoLine
globals()['SalesCreditMemoLine'] = SalesCreditMemoLine
from pybusinesscentral.model.inline_response20044 import InlineResponse20044


class TestInlineResponse20044(unittest.TestCase):
    """InlineResponse20044 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20044(self):
        """Test InlineResponse20044"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20044()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
