"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pybusinesscentral
from pybusinesscentral.model.aged_accounts_payable import AgedAccountsPayable


class TestAgedAccountsPayable(unittest.TestCase):
    """AgedAccountsPayable unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAgedAccountsPayable(self):
        """Test AgedAccountsPayable"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AgedAccountsPayable()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
