"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pybusinesscentral
from pybusinesscentral.model.journal import Journal
globals()['Journal'] = Journal
from pybusinesscentral.model.inline_response20015 import InlineResponse20015


class TestInlineResponse20015(unittest.TestCase):
    """InlineResponse20015 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20015(self):
        """Test InlineResponse20015"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20015()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
