# coding: utf-8

"""
    (v2.0) Dynamics 365 Business Central

    (v2.0) Business Central Standard APIs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pybusinesscentral.api.sales_credit_memo_api import SalesCreditMemoApi


class TestSalesCreditMemoApi(unittest.TestCase):
    """SalesCreditMemoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SalesCreditMemoApi()

    def tearDown(self) -> None:
        pass

    def test_delete_sales_credit_memo(self) -> None:
        """Test case for delete_sales_credit_memo

        Deletes an object of type salesCreditMemo in Dynamics 365 Business Central
        """
        pass

    def test_get_sales_credit_memo(self) -> None:
        """Test case for get_sales_credit_memo

        Retrieve the properties and relationships of an object of type salesCreditMemo for Dynamics 365 Business Central.
        """
        pass

    def test_list_sales_credit_memos(self) -> None:
        """Test case for list_sales_credit_memos

        Returns a list of salesCreditMemos
        """
        pass

    def test_patch_sales_credit_memo(self) -> None:
        """Test case for patch_sales_credit_memo

        Updates an object of type salesCreditMemo in Dynamics 365 Business Central
        """
        pass

    def test_post_action_sales_credit_memos(self) -> None:
        """Test case for post_action_sales_credit_memos

        Performs the post action for salesCreditMemos entity
        """
        pass

    def test_post_and_send_action_sales_credit_memos(self) -> None:
        """Test case for post_and_send_action_sales_credit_memos

        Performs the postAndSend action for salesCreditMemos entity
        """
        pass

    def test_post_sales_credit_memo(self) -> None:
        """Test case for post_sales_credit_memo

        Creates an object of type salesCreditMemo in Dynamics 365 Business Central
        """
        pass


if __name__ == '__main__':
    unittest.main()
