"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pybusinesscentral
from pybusinesscentral.model.payment_term import PaymentTerm
globals()['PaymentTerm'] = PaymentTerm
from pybusinesscentral.model.inline_response20026 import InlineResponse20026


class TestInlineResponse20026(unittest.TestCase):
    """InlineResponse20026 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20026(self):
        """Test InlineResponse20026"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20026()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
