# coding: utf-8

"""
    (v2.0) Dynamics 365 Business Central

    (v2.0) Business Central Standard APIs

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pybusinesscentral.api.sales_invoice_api import SalesInvoiceApi


class TestSalesInvoiceApi(unittest.TestCase):
    """SalesInvoiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SalesInvoiceApi()

    def tearDown(self) -> None:
        pass

    def test_delete_sales_invoice(self) -> None:
        """Test case for delete_sales_invoice

        Deletes an object of type salesInvoice in Dynamics 365 Business Central
        """
        pass

    def test_get_sales_invoice(self) -> None:
        """Test case for get_sales_invoice

        Retrieve the properties and relationships of an object of type salesInvoice for Dynamics 365 Business Central.
        """
        pass

    def test_list_sales_invoices(self) -> None:
        """Test case for list_sales_invoices

        Returns a list of salesInvoices
        """
        pass

    def test_patch_sales_invoice(self) -> None:
        """Test case for patch_sales_invoice

        Updates an object of type salesInvoice in Dynamics 365 Business Central
        """
        pass

    def test_post_action_sales_invoices(self) -> None:
        """Test case for post_action_sales_invoices

        Performs the post action for salesInvoices entity
        """
        pass

    def test_post_sales_invoice(self) -> None:
        """Test case for post_sales_invoice

        Creates an object of type salesInvoice in Dynamics 365 Business Central
        """
        pass


if __name__ == '__main__':
    unittest.main()
