"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pybusinesscentral
from pybusinesscentral.model.dimension import Dimension
globals()['Dimension'] = Dimension
from pybusinesscentral.model.inline_response20023 import InlineResponse20023


class TestInlineResponse20023(unittest.TestCase):
    """InlineResponse20023 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20023(self):
        """Test InlineResponse20023"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20023()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
