"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pybusinesscentral
from pybusinesscentral.api.balance_sheet_api import BalanceSheetApi  # noqa: E501


class TestBalanceSheetApi(unittest.TestCase):
    """BalanceSheetApi unit test stubs"""

    def setUp(self):
        self.api = BalanceSheetApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_balance_sheet(self):
        """Test case for get_balance_sheet

        Retrieve the properties and relationships of an object of type balanceSheet for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_list_balance_sheet(self):
        """Test case for list_balance_sheet

        Returns a list of balanceSheet  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
