"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pybusinesscentral
from pybusinesscentral.api.aged_accounts_receivable_api import AgedAccountsReceivableApi  # noqa: E501


class TestAgedAccountsReceivableApi(unittest.TestCase):
    """AgedAccountsReceivableApi unit test stubs"""

    def setUp(self):
        self.api = AgedAccountsReceivableApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_aged_accounts_receivable(self):
        """Test case for get_aged_accounts_receivable

        Retrieve the properties and relationships of an object of type agedAccountsReceivable for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_list_aged_accounts_receivable(self):
        """Test case for list_aged_accounts_receivable

        Returns a list of agedAccountsReceivable  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
