"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import unittest

import pybusinesscentral
from pybusinesscentral.api.customer_api import CustomerApi  # noqa: E501


class TestCustomerApi(unittest.TestCase):
    """CustomerApi unit test stubs"""

    def setUp(self):
        self.api = CustomerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_customer(self):
        """Test case for delete_customer

        Deletes an object of type customer in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_get_customer(self):
        """Test case for get_customer

        Retrieve the properties and relationships of an object of type customer for Dynamics 365 Business Central.  # noqa: E501
        """
        pass

    def test_list_customers(self):
        """Test case for list_customers

        Returns a list of customers  # noqa: E501
        """
        pass

    def test_patch_customer(self):
        """Test case for patch_customer

        Updates an object of type customer in Dynamics 365 Business Central  # noqa: E501
        """
        pass

    def test_post_customer(self):
        """Test case for post_customer

        Creates an object of type customer in Dynamics 365 Business Central  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
