"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import pybusinesscentral
from pybusinesscentral.model.journal_line import JournalLine
globals()['JournalLine'] = JournalLine
from pybusinesscentral.model.inline_response20016 import InlineResponse20016


class TestInlineResponse20016(unittest.TestCase):
    """InlineResponse20016 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse20016(self):
        """Test InlineResponse20016"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InlineResponse20016()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
