"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from pybusinesscentral.api_client import ApiClient, Endpoint as _Endpoint
from pybusinesscentral.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from pybusinesscentral.model.attachments import Attachments
from pybusinesscentral.model.inline_response20017 import InlineResponse20017


class AttachmentsApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __delete_attachments(
            self,
            company_id,
            attachments_parent_id,
            attachments_id,
            **kwargs
        ):
            """Deletes an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.delete_attachments(company_id, attachments_parent_id, attachments_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            return self.call_with_http_info(**kwargs)

        self.delete_attachments = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'delete_attachments',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'required': [
                    'company_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__delete_attachments
        )

        def __delete_attachments_for_journal_line(
            self,
            company_id,
            journal_line_id,
            attachments_parent_id,
            attachments_id,
            **kwargs
        ):
            """Deletes an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.delete_attachments_for_journal_line(company_id, journal_line_id, attachments_parent_id, attachments_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_line_id (str): (v1.0) id for journalLine
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_line_id'] = \
                journal_line_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            return self.call_with_http_info(**kwargs)

        self.delete_attachments_for_journal_line = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journalLines({journalLine_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'delete_attachments_for_journal_line',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'required': [
                    'company_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_line_id': 'journalLine_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_line_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__delete_attachments_for_journal_line
        )

        def __delete_attachments_for_journal_line_for_journal(
            self,
            company_id,
            journal_id,
            journal_line_id,
            attachments_parent_id,
            attachments_id,
            **kwargs
        ):
            """Deletes an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.delete_attachments_for_journal_line_for_journal(company_id, journal_id, journal_line_id, attachments_parent_id, attachments_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_id (str): (v1.0) id for journal
                journal_line_id (str): (v1.0) id for journalLine
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_id'] = \
                journal_id
            kwargs['journal_line_id'] = \
                journal_line_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            return self.call_with_http_info(**kwargs)

        self.delete_attachments_for_journal_line_for_journal = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journals({journal_id})/journalLines({journalLine_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'delete_attachments_for_journal_line_for_journal',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'required': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_id': 'journal_id',
                    'journal_line_id': 'journalLine_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_id': 'path',
                    'journal_line_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__delete_attachments_for_journal_line_for_journal
        )

        def __get_attachments(
            self,
            company_id,
            attachments_parent_id,
            attachments_id,
            **kwargs
        ):
            """Retrieve the properties and relationships of an object of type attachments for Dynamics 365 Business Central.  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_attachments(company_id, attachments_parent_id, attachments_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments

            Keyword Args:
                select ([str]): (v1.0) Selected properties to be retrieved. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            return self.call_with_http_info(**kwargs)

        self.get_attachments = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'get_attachments',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'select',
                ],
                'required': [
                    'company_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'select',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('select',): {

                        "PARENTID": "parentId",
                        "ID": "id",
                        "FILENAME": "fileName",
                        "BYTESIZE": "byteSize",
                        "CONTENT": "content",
                        "LASTMODIFIEDDATETIME": "lastModifiedDateTime"
                    },
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                    'select':
                        ([str],),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                    'select': '$select',
                },
                'location_map': {
                    'company_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                    'select': 'query',
                },
                'collection_format_map': {
                    'select': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_attachments
        )

        def __get_attachments_for_journal_line(
            self,
            company_id,
            journal_line_id,
            attachments_parent_id,
            attachments_id,
            **kwargs
        ):
            """Retrieve the properties and relationships of an object of type attachments for Dynamics 365 Business Central.  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_attachments_for_journal_line(company_id, journal_line_id, attachments_parent_id, attachments_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_line_id (str): (v1.0) id for journalLine
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments

            Keyword Args:
                select ([str]): (v1.0) Selected properties to be retrieved. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_line_id'] = \
                journal_line_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            return self.call_with_http_info(**kwargs)

        self.get_attachments_for_journal_line = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journalLines({journalLine_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'get_attachments_for_journal_line',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'select',
                ],
                'required': [
                    'company_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'select',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('select',): {

                        "PARENTID": "parentId",
                        "ID": "id",
                        "FILENAME": "fileName",
                        "BYTESIZE": "byteSize",
                        "CONTENT": "content",
                        "LASTMODIFIEDDATETIME": "lastModifiedDateTime"
                    },
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                    'select':
                        ([str],),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_line_id': 'journalLine_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                    'select': '$select',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_line_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                    'select': 'query',
                },
                'collection_format_map': {
                    'select': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_attachments_for_journal_line
        )

        def __get_attachments_for_journal_line_for_journal(
            self,
            company_id,
            journal_id,
            journal_line_id,
            attachments_parent_id,
            attachments_id,
            **kwargs
        ):
            """Retrieve the properties and relationships of an object of type attachments for Dynamics 365 Business Central.  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_attachments_for_journal_line_for_journal(company_id, journal_id, journal_line_id, attachments_parent_id, attachments_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_id (str): (v1.0) id for journal
                journal_line_id (str): (v1.0) id for journalLine
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments

            Keyword Args:
                select ([str]): (v1.0) Selected properties to be retrieved. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_id'] = \
                journal_id
            kwargs['journal_line_id'] = \
                journal_line_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            return self.call_with_http_info(**kwargs)

        self.get_attachments_for_journal_line_for_journal = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journals({journal_id})/journalLines({journalLine_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'get_attachments_for_journal_line_for_journal',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'select',
                ],
                'required': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'select',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('select',): {

                        "PARENTID": "parentId",
                        "ID": "id",
                        "FILENAME": "fileName",
                        "BYTESIZE": "byteSize",
                        "CONTENT": "content",
                        "LASTMODIFIEDDATETIME": "lastModifiedDateTime"
                    },
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                    'select':
                        ([str],),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_id': 'journal_id',
                    'journal_line_id': 'journalLine_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                    'select': '$select',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_id': 'path',
                    'journal_line_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                    'select': 'query',
                },
                'collection_format_map': {
                    'select': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_attachments_for_journal_line_for_journal
        )

        def __list_attachments(
            self,
            company_id,
            **kwargs
        ):
            """Returns a list of attachments  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.list_attachments(company_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company

            Keyword Args:
                top (int): (v1.0) Number of items to return from the top of the list. [optional]
                skip (int): (v1.0) Number of items to skip from the list. [optional]
                limit (int): (v1.0) Number of items to return from the list. [optional]
                filter (str): (v1.0) Filtering expression. [optional]
                select ([str]): (v1.0) Selected properties to be retrieved. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                InlineResponse20017
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            return self.call_with_http_info(**kwargs)

        self.list_attachments = _Endpoint(
            settings={
                'response_type': (InlineResponse20017,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/attachments',
                'operation_id': 'list_attachments',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'top',
                    'skip',
                    'limit',
                    'filter',
                    'select',
                ],
                'required': [
                    'company_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'select',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('select',): {

                        "PARENTID": "parentId",
                        "ID": "id",
                        "FILENAME": "fileName",
                        "BYTESIZE": "byteSize",
                        "CONTENT": "content",
                        "LASTMODIFIEDDATETIME": "lastModifiedDateTime"
                    },
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'top':
                        (int,),
                    'skip':
                        (int,),
                    'limit':
                        (int,),
                    'filter':
                        (str,),
                    'select':
                        ([str],),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'top': '$top',
                    'skip': '$skip',
                    'limit': '$limit',
                    'filter': '$filter',
                    'select': '$select',
                },
                'location_map': {
                    'company_id': 'path',
                    'top': 'query',
                    'skip': 'query',
                    'limit': 'query',
                    'filter': 'query',
                    'select': 'query',
                },
                'collection_format_map': {
                    'select': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__list_attachments
        )

        def __list_attachments_for_journal_line(
            self,
            company_id,
            journal_line_id,
            **kwargs
        ):
            """Returns a list of attachments  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.list_attachments_for_journal_line(company_id, journal_line_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_line_id (str): (v1.0) id for journalLine

            Keyword Args:
                top (int): (v1.0) Number of items to return from the top of the list. [optional]
                skip (int): (v1.0) Number of items to skip from the list. [optional]
                limit (int): (v1.0) Number of items to return from the list. [optional]
                filter (str): (v1.0) Filtering expression. [optional]
                select ([str]): (v1.0) Selected properties to be retrieved. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                InlineResponse20017
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_line_id'] = \
                journal_line_id
            return self.call_with_http_info(**kwargs)

        self.list_attachments_for_journal_line = _Endpoint(
            settings={
                'response_type': (InlineResponse20017,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journalLines({journalLine_id})/attachments',
                'operation_id': 'list_attachments_for_journal_line',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_line_id',
                    'top',
                    'skip',
                    'limit',
                    'filter',
                    'select',
                ],
                'required': [
                    'company_id',
                    'journal_line_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'select',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('select',): {

                        "PARENTID": "parentId",
                        "ID": "id",
                        "FILENAME": "fileName",
                        "BYTESIZE": "byteSize",
                        "CONTENT": "content",
                        "LASTMODIFIEDDATETIME": "lastModifiedDateTime"
                    },
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'top':
                        (int,),
                    'skip':
                        (int,),
                    'limit':
                        (int,),
                    'filter':
                        (str,),
                    'select':
                        ([str],),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_line_id': 'journalLine_id',
                    'top': '$top',
                    'skip': '$skip',
                    'limit': '$limit',
                    'filter': '$filter',
                    'select': '$select',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_line_id': 'path',
                    'top': 'query',
                    'skip': 'query',
                    'limit': 'query',
                    'filter': 'query',
                    'select': 'query',
                },
                'collection_format_map': {
                    'select': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__list_attachments_for_journal_line
        )

        def __list_attachments_for_journal_line_for_journal(
            self,
            company_id,
            journal_id,
            journal_line_id,
            **kwargs
        ):
            """Returns a list of attachments  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.list_attachments_for_journal_line_for_journal(company_id, journal_id, journal_line_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_id (str): (v1.0) id for journal
                journal_line_id (str): (v1.0) id for journalLine

            Keyword Args:
                top (int): (v1.0) Number of items to return from the top of the list. [optional]
                skip (int): (v1.0) Number of items to skip from the list. [optional]
                limit (int): (v1.0) Number of items to return from the list. [optional]
                filter (str): (v1.0) Filtering expression. [optional]
                select ([str]): (v1.0) Selected properties to be retrieved. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                InlineResponse20017
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_id'] = \
                journal_id
            kwargs['journal_line_id'] = \
                journal_line_id
            return self.call_with_http_info(**kwargs)

        self.list_attachments_for_journal_line_for_journal = _Endpoint(
            settings={
                'response_type': (InlineResponse20017,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journals({journal_id})/journalLines({journalLine_id})/attachments',
                'operation_id': 'list_attachments_for_journal_line_for_journal',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'top',
                    'skip',
                    'limit',
                    'filter',
                    'select',
                ],
                'required': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'select',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('select',): {

                        "PARENTID": "parentId",
                        "ID": "id",
                        "FILENAME": "fileName",
                        "BYTESIZE": "byteSize",
                        "CONTENT": "content",
                        "LASTMODIFIEDDATETIME": "lastModifiedDateTime"
                    },
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'top':
                        (int,),
                    'skip':
                        (int,),
                    'limit':
                        (int,),
                    'filter':
                        (str,),
                    'select':
                        ([str],),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_id': 'journal_id',
                    'journal_line_id': 'journalLine_id',
                    'top': '$top',
                    'skip': '$skip',
                    'limit': '$limit',
                    'filter': '$filter',
                    'select': '$select',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_id': 'path',
                    'journal_line_id': 'path',
                    'top': 'query',
                    'skip': 'query',
                    'limit': 'query',
                    'filter': 'query',
                    'select': 'query',
                },
                'collection_format_map': {
                    'select': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__list_attachments_for_journal_line_for_journal
        )

        def __patch_attachments(
            self,
            company_id,
            attachments_parent_id,
            attachments_id,
            content_type,
            if_match,
            attachments,
            **kwargs
        ):
            """Updates an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.patch_attachments(company_id, attachments_parent_id, attachments_id, content_type, if_match, attachments, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments
                content_type (str): (v1.0) application/json
                if_match (str): (v1.0) Required. When this request header is included and the eTag provided does not match the current tag on the entity, this will not be updated.
                attachments (Attachments):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            kwargs['content_type'] = \
                content_type
            kwargs['if_match'] = \
                if_match
            kwargs['attachments'] = \
                attachments
            return self.call_with_http_info(**kwargs)

        self.patch_attachments = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'patch_attachments',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'content_type',
                    'if_match',
                    'attachments',
                ],
                'required': [
                    'company_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'content_type',
                    'if_match',
                    'attachments',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                    'content_type':
                        (str,),
                    'if_match':
                        (str,),
                    'attachments':
                        (Attachments,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                    'content_type': 'Content-Type',
                    'if_match': 'If-Match',
                },
                'location_map': {
                    'company_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                    'content_type': 'header',
                    'if_match': 'header',
                    'attachments': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__patch_attachments
        )

        def __patch_attachments_for_journal_line(
            self,
            company_id,
            journal_line_id,
            attachments_parent_id,
            attachments_id,
            content_type,
            if_match,
            attachments,
            **kwargs
        ):
            """Updates an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.patch_attachments_for_journal_line(company_id, journal_line_id, attachments_parent_id, attachments_id, content_type, if_match, attachments, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_line_id (str): (v1.0) id for journalLine
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments
                content_type (str): (v1.0) application/json
                if_match (str): (v1.0) Required. When this request header is included and the eTag provided does not match the current tag on the entity, this will not be updated.
                attachments (Attachments):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_line_id'] = \
                journal_line_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            kwargs['content_type'] = \
                content_type
            kwargs['if_match'] = \
                if_match
            kwargs['attachments'] = \
                attachments
            return self.call_with_http_info(**kwargs)

        self.patch_attachments_for_journal_line = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journalLines({journalLine_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'patch_attachments_for_journal_line',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'content_type',
                    'if_match',
                    'attachments',
                ],
                'required': [
                    'company_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'content_type',
                    'if_match',
                    'attachments',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                    'content_type':
                        (str,),
                    'if_match':
                        (str,),
                    'attachments':
                        (Attachments,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_line_id': 'journalLine_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                    'content_type': 'Content-Type',
                    'if_match': 'If-Match',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_line_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                    'content_type': 'header',
                    'if_match': 'header',
                    'attachments': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__patch_attachments_for_journal_line
        )

        def __patch_attachments_for_journal_line_for_journal(
            self,
            company_id,
            journal_id,
            journal_line_id,
            attachments_parent_id,
            attachments_id,
            content_type,
            if_match,
            attachments,
            **kwargs
        ):
            """Updates an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.patch_attachments_for_journal_line_for_journal(company_id, journal_id, journal_line_id, attachments_parent_id, attachments_id, content_type, if_match, attachments, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_id (str): (v1.0) id for journal
                journal_line_id (str): (v1.0) id for journalLine
                attachments_parent_id (str): (v1.0) parentId for attachments
                attachments_id (str): (v1.0) id for attachments
                content_type (str): (v1.0) application/json
                if_match (str): (v1.0) Required. When this request header is included and the eTag provided does not match the current tag on the entity, this will not be updated.
                attachments (Attachments):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_id'] = \
                journal_id
            kwargs['journal_line_id'] = \
                journal_line_id
            kwargs['attachments_parent_id'] = \
                attachments_parent_id
            kwargs['attachments_id'] = \
                attachments_id
            kwargs['content_type'] = \
                content_type
            kwargs['if_match'] = \
                if_match
            kwargs['attachments'] = \
                attachments
            return self.call_with_http_info(**kwargs)

        self.patch_attachments_for_journal_line_for_journal = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journals({journal_id})/journalLines({journalLine_id})/attachments({attachments_parentId},{attachments_id})',
                'operation_id': 'patch_attachments_for_journal_line_for_journal',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'content_type',
                    'if_match',
                    'attachments',
                ],
                'required': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'attachments_parent_id',
                    'attachments_id',
                    'content_type',
                    'if_match',
                    'attachments',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'attachments_parent_id':
                        (str,),
                    'attachments_id':
                        (str,),
                    'content_type':
                        (str,),
                    'if_match':
                        (str,),
                    'attachments':
                        (Attachments,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_id': 'journal_id',
                    'journal_line_id': 'journalLine_id',
                    'attachments_parent_id': 'attachments_parentId',
                    'attachments_id': 'attachments_id',
                    'content_type': 'Content-Type',
                    'if_match': 'If-Match',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_id': 'path',
                    'journal_line_id': 'path',
                    'attachments_parent_id': 'path',
                    'attachments_id': 'path',
                    'content_type': 'header',
                    'if_match': 'header',
                    'attachments': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__patch_attachments_for_journal_line_for_journal
        )

        def __post_attachments(
            self,
            company_id,
            content_type,
            attachments,
            **kwargs
        ):
            """Creates an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_attachments(company_id, content_type, attachments, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                content_type (str): (v1.0) application/json
                attachments (Attachments):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['content_type'] = \
                content_type
            kwargs['attachments'] = \
                attachments
            return self.call_with_http_info(**kwargs)

        self.post_attachments = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/attachments',
                'operation_id': 'post_attachments',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'content_type',
                    'attachments',
                ],
                'required': [
                    'company_id',
                    'content_type',
                    'attachments',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'content_type':
                        (str,),
                    'attachments':
                        (Attachments,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'company_id': 'path',
                    'content_type': 'header',
                    'attachments': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_attachments
        )

        def __post_attachments_for_journal_line(
            self,
            company_id,
            journal_line_id,
            content_type,
            attachments,
            **kwargs
        ):
            """Creates an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_attachments_for_journal_line(company_id, journal_line_id, content_type, attachments, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_line_id (str): (v1.0) id for journalLine
                content_type (str): (v1.0) application/json
                attachments (Attachments):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_line_id'] = \
                journal_line_id
            kwargs['content_type'] = \
                content_type
            kwargs['attachments'] = \
                attachments
            return self.call_with_http_info(**kwargs)

        self.post_attachments_for_journal_line = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journalLines({journalLine_id})/attachments',
                'operation_id': 'post_attachments_for_journal_line',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_line_id',
                    'content_type',
                    'attachments',
                ],
                'required': [
                    'company_id',
                    'journal_line_id',
                    'content_type',
                    'attachments',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'content_type':
                        (str,),
                    'attachments':
                        (Attachments,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_line_id': 'journalLine_id',
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_line_id': 'path',
                    'content_type': 'header',
                    'attachments': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_attachments_for_journal_line
        )

        def __post_attachments_for_journal_line_for_journal(
            self,
            company_id,
            journal_id,
            journal_line_id,
            content_type,
            attachments,
            **kwargs
        ):
            """Creates an object of type attachments in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_attachments_for_journal_line_for_journal(company_id, journal_id, journal_line_id, content_type, attachments, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                journal_id (str): (v1.0) id for journal
                journal_line_id (str): (v1.0) id for journalLine
                content_type (str): (v1.0) application/json
                attachments (Attachments):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                Attachments
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['journal_id'] = \
                journal_id
            kwargs['journal_line_id'] = \
                journal_line_id
            kwargs['content_type'] = \
                content_type
            kwargs['attachments'] = \
                attachments
            return self.call_with_http_info(**kwargs)

        self.post_attachments_for_journal_line_for_journal = _Endpoint(
            settings={
                'response_type': (Attachments,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/journals({journal_id})/journalLines({journalLine_id})/attachments',
                'operation_id': 'post_attachments_for_journal_line_for_journal',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'content_type',
                    'attachments',
                ],
                'required': [
                    'company_id',
                    'journal_id',
                    'journal_line_id',
                    'content_type',
                    'attachments',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'journal_id':
                        (str,),
                    'journal_line_id':
                        (str,),
                    'content_type':
                        (str,),
                    'attachments':
                        (Attachments,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'journal_id': 'journal_id',
                    'journal_line_id': 'journalLine_id',
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'company_id': 'path',
                    'journal_id': 'path',
                    'journal_line_id': 'path',
                    'content_type': 'header',
                    'attachments': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_attachments_for_journal_line_for_journal
        )
