"""
    (v1.0) Dynamics 365 Business Central

    (v1.0) Business Central Standard APIs  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from pybusinesscentral.api_client import ApiClient, Endpoint as _Endpoint
from pybusinesscentral.model_utils import (  # noqa: F401
    check_allowed_values,
    check_validations,
    date,
    datetime,
    file_type,
    none_type,
    validate_and_convert_types
)
from pybusinesscentral.model.inline_response20043 import InlineResponse20043
from pybusinesscentral.model.sales_credit_memo import SalesCreditMemo


class SalesCreditMemoApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

        def __cancel_action_sales_credit_memos(
            self,
            company_id,
            sales_credit_memo_id,
            **kwargs
        ):
            """Performs the cancel action for salesCreditMemos entity  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.cancel_action_sales_credit_memos(company_id, sales_credit_memo_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                sales_credit_memo_id (str): (v1.0) id for salesCreditMemo

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['sales_credit_memo_id'] = \
                sales_credit_memo_id
            return self.call_with_http_info(**kwargs)

        self.cancel_action_sales_credit_memos = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos({salesCreditMemo_id})/Microsoft.NAV.cancel',
                'operation_id': 'cancel_action_sales_credit_memos',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'required': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'sales_credit_memo_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'sales_credit_memo_id': 'salesCreditMemo_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'sales_credit_memo_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__cancel_action_sales_credit_memos
        )

        def __cancel_and_send_action_sales_credit_memos(
            self,
            company_id,
            sales_credit_memo_id,
            **kwargs
        ):
            """Performs the cancelAndSend action for salesCreditMemos entity  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.cancel_and_send_action_sales_credit_memos(company_id, sales_credit_memo_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                sales_credit_memo_id (str): (v1.0) id for salesCreditMemo

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['sales_credit_memo_id'] = \
                sales_credit_memo_id
            return self.call_with_http_info(**kwargs)

        self.cancel_and_send_action_sales_credit_memos = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos({salesCreditMemo_id})/Microsoft.NAV.cancelAndSend',
                'operation_id': 'cancel_and_send_action_sales_credit_memos',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'required': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'sales_credit_memo_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'sales_credit_memo_id': 'salesCreditMemo_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'sales_credit_memo_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__cancel_and_send_action_sales_credit_memos
        )

        def __delete_sales_credit_memo(
            self,
            company_id,
            sales_credit_memo_id,
            **kwargs
        ):
            """Deletes an object of type salesCreditMemo in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.delete_sales_credit_memo(company_id, sales_credit_memo_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                sales_credit_memo_id (str): (v1.0) id for salesCreditMemo

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['sales_credit_memo_id'] = \
                sales_credit_memo_id
            return self.call_with_http_info(**kwargs)

        self.delete_sales_credit_memo = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos({salesCreditMemo_id})',
                'operation_id': 'delete_sales_credit_memo',
                'http_method': 'DELETE',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'required': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'sales_credit_memo_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'sales_credit_memo_id': 'salesCreditMemo_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'sales_credit_memo_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__delete_sales_credit_memo
        )

        def __get_sales_credit_memo(
            self,
            company_id,
            sales_credit_memo_id,
            **kwargs
        ):
            """Retrieve the properties and relationships of an object of type salesCreditMemo for Dynamics 365 Business Central.  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.get_sales_credit_memo(company_id, sales_credit_memo_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                sales_credit_memo_id (str): (v1.0) id for salesCreditMemo

            Keyword Args:
                expand ([str]): (v1.0) Entities to expand. [optional]
                select ([str]): (v1.0) Selected properties to be retrieved. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                SalesCreditMemo
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['sales_credit_memo_id'] = \
                sales_credit_memo_id
            return self.call_with_http_info(**kwargs)

        self.get_sales_credit_memo = _Endpoint(
            settings={
                'response_type': (SalesCreditMemo,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos({salesCreditMemo_id})',
                'operation_id': 'get_sales_credit_memo',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'sales_credit_memo_id',
                    'expand',
                    'select',
                ],
                'required': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'expand',
                    'select',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('expand',): {

                        "SALESCREDITMEMOLINES": "salesCreditMemoLines",
                        "PDFDOCUMENT": "pdfDocument",
                        "CUSTOMER": "customer",
                        "CURRENCY": "currency",
                        "PAYMENTTERM": "paymentTerm",
                        "SHIPMENTMETHOD": "shipmentMethod"
                    },
                    ('select',): {

                        "ID": "id",
                        "NUMBER": "number",
                        "EXTERNALDOCUMENTNUMBER": "externalDocumentNumber",
                        "CREDITMEMODATE": "creditMemoDate",
                        "DUEDATE": "dueDate",
                        "CUSTOMERID": "customerId",
                        "CONTACTID": "contactId",
                        "CUSTOMERNUMBER": "customerNumber",
                        "CUSTOMERNAME": "customerName",
                        "BILLTONAME": "billToName",
                        "BILLTOCUSTOMERID": "billToCustomerId",
                        "BILLTOCUSTOMERNUMBER": "billToCustomerNumber",
                        "SELLINGPOSTALADDRESS": "sellingPostalAddress",
                        "BILLINGPOSTALADDRESS": "billingPostalAddress",
                        "CURRENCYID": "currencyId",
                        "CURRENCYCODE": "currencyCode",
                        "PAYMENTTERMSID": "paymentTermsId",
                        "SHIPMENTMETHODID": "shipmentMethodId",
                        "SALESPERSON": "salesperson",
                        "PRICESINCLUDETAX": "pricesIncludeTax",
                        "DISCOUNTAMOUNT": "discountAmount",
                        "DISCOUNTAPPLIEDBEFORETAX": "discountAppliedBeforeTax",
                        "TOTALAMOUNTEXCLUDINGTAX": "totalAmountExcludingTax",
                        "TOTALTAXAMOUNT": "totalTaxAmount",
                        "TOTALAMOUNTINCLUDINGTAX": "totalAmountIncludingTax",
                        "STATUS": "status",
                        "LASTMODIFIEDDATETIME": "lastModifiedDateTime",
                        "INVOICEID": "invoiceId",
                        "INVOICENUMBER": "invoiceNumber",
                        "PHONENUMBER": "phoneNumber",
                        "EMAIL": "email"
                    },
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'sales_credit_memo_id':
                        (str,),
                    'expand':
                        ([str],),
                    'select':
                        ([str],),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'sales_credit_memo_id': 'salesCreditMemo_id',
                    'expand': '$expand',
                    'select': '$select',
                },
                'location_map': {
                    'company_id': 'path',
                    'sales_credit_memo_id': 'path',
                    'expand': 'query',
                    'select': 'query',
                },
                'collection_format_map': {
                    'expand': 'csv',
                    'select': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__get_sales_credit_memo
        )

        def __list_sales_credit_memos(
            self,
            company_id,
            **kwargs
        ):
            """Returns a list of salesCreditMemos  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.list_sales_credit_memos(company_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company

            Keyword Args:
                top (int): (v1.0) Number of items to return from the top of the list. [optional]
                skip (int): (v1.0) Number of items to skip from the list. [optional]
                limit (int): (v1.0) Number of items to return from the list. [optional]
                filter (str): (v1.0) Filtering expression. [optional]
                expand ([str]): (v1.0) Entities to expand. [optional]
                select ([str]): (v1.0) Selected properties to be retrieved. [optional]
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                InlineResponse20043
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            return self.call_with_http_info(**kwargs)

        self.list_sales_credit_memos = _Endpoint(
            settings={
                'response_type': (InlineResponse20043,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos',
                'operation_id': 'list_sales_credit_memos',
                'http_method': 'GET',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'top',
                    'skip',
                    'limit',
                    'filter',
                    'expand',
                    'select',
                ],
                'required': [
                    'company_id',
                ],
                'nullable': [
                ],
                'enum': [
                    'expand',
                    'select',
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                    ('expand',): {

                        "SALESCREDITMEMOLINES": "salesCreditMemoLines",
                        "PDFDOCUMENT": "pdfDocument",
                        "CUSTOMER": "customer",
                        "CURRENCY": "currency",
                        "PAYMENTTERM": "paymentTerm",
                        "SHIPMENTMETHOD": "shipmentMethod"
                    },
                    ('select',): {

                        "ID": "id",
                        "NUMBER": "number",
                        "EXTERNALDOCUMENTNUMBER": "externalDocumentNumber",
                        "CREDITMEMODATE": "creditMemoDate",
                        "DUEDATE": "dueDate",
                        "CUSTOMERID": "customerId",
                        "CONTACTID": "contactId",
                        "CUSTOMERNUMBER": "customerNumber",
                        "CUSTOMERNAME": "customerName",
                        "BILLTONAME": "billToName",
                        "BILLTOCUSTOMERID": "billToCustomerId",
                        "BILLTOCUSTOMERNUMBER": "billToCustomerNumber",
                        "SELLINGPOSTALADDRESS": "sellingPostalAddress",
                        "BILLINGPOSTALADDRESS": "billingPostalAddress",
                        "CURRENCYID": "currencyId",
                        "CURRENCYCODE": "currencyCode",
                        "PAYMENTTERMSID": "paymentTermsId",
                        "SHIPMENTMETHODID": "shipmentMethodId",
                        "SALESPERSON": "salesperson",
                        "PRICESINCLUDETAX": "pricesIncludeTax",
                        "DISCOUNTAMOUNT": "discountAmount",
                        "DISCOUNTAPPLIEDBEFORETAX": "discountAppliedBeforeTax",
                        "TOTALAMOUNTEXCLUDINGTAX": "totalAmountExcludingTax",
                        "TOTALTAXAMOUNT": "totalTaxAmount",
                        "TOTALAMOUNTINCLUDINGTAX": "totalAmountIncludingTax",
                        "STATUS": "status",
                        "LASTMODIFIEDDATETIME": "lastModifiedDateTime",
                        "INVOICEID": "invoiceId",
                        "INVOICENUMBER": "invoiceNumber",
                        "PHONENUMBER": "phoneNumber",
                        "EMAIL": "email"
                    },
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'top':
                        (int,),
                    'skip':
                        (int,),
                    'limit':
                        (int,),
                    'filter':
                        (str,),
                    'expand':
                        ([str],),
                    'select':
                        ([str],),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'top': '$top',
                    'skip': '$skip',
                    'limit': '$limit',
                    'filter': '$filter',
                    'expand': '$expand',
                    'select': '$select',
                },
                'location_map': {
                    'company_id': 'path',
                    'top': 'query',
                    'skip': 'query',
                    'limit': 'query',
                    'filter': 'query',
                    'expand': 'query',
                    'select': 'query',
                },
                'collection_format_map': {
                    'expand': 'csv',
                    'select': 'csv',
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [],
            },
            api_client=api_client,
            callable=__list_sales_credit_memos
        )

        def __patch_sales_credit_memo(
            self,
            company_id,
            sales_credit_memo_id,
            content_type,
            if_match,
            sales_credit_memo,
            **kwargs
        ):
            """Updates an object of type salesCreditMemo in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.patch_sales_credit_memo(company_id, sales_credit_memo_id, content_type, if_match, sales_credit_memo, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                sales_credit_memo_id (str): (v1.0) id for salesCreditMemo
                content_type (str): (v1.0) application/json
                if_match (str): (v1.0) Required. When this request header is included and the eTag provided does not match the current tag on the entity, this will not be updated.
                sales_credit_memo (SalesCreditMemo):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                SalesCreditMemo
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['sales_credit_memo_id'] = \
                sales_credit_memo_id
            kwargs['content_type'] = \
                content_type
            kwargs['if_match'] = \
                if_match
            kwargs['sales_credit_memo'] = \
                sales_credit_memo
            return self.call_with_http_info(**kwargs)

        self.patch_sales_credit_memo = _Endpoint(
            settings={
                'response_type': (SalesCreditMemo,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos({salesCreditMemo_id})',
                'operation_id': 'patch_sales_credit_memo',
                'http_method': 'PATCH',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'sales_credit_memo_id',
                    'content_type',
                    'if_match',
                    'sales_credit_memo',
                ],
                'required': [
                    'company_id',
                    'sales_credit_memo_id',
                    'content_type',
                    'if_match',
                    'sales_credit_memo',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'sales_credit_memo_id':
                        (str,),
                    'content_type':
                        (str,),
                    'if_match':
                        (str,),
                    'sales_credit_memo':
                        (SalesCreditMemo,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'sales_credit_memo_id': 'salesCreditMemo_id',
                    'content_type': 'Content-Type',
                    'if_match': 'If-Match',
                },
                'location_map': {
                    'company_id': 'path',
                    'sales_credit_memo_id': 'path',
                    'content_type': 'header',
                    'if_match': 'header',
                    'sales_credit_memo': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__patch_sales_credit_memo
        )

        def __post_action_sales_credit_memos(
            self,
            company_id,
            sales_credit_memo_id,
            **kwargs
        ):
            """Performs the post action for salesCreditMemos entity  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_action_sales_credit_memos(company_id, sales_credit_memo_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                sales_credit_memo_id (str): (v1.0) id for salesCreditMemo

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['sales_credit_memo_id'] = \
                sales_credit_memo_id
            return self.call_with_http_info(**kwargs)

        self.post_action_sales_credit_memos = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos({salesCreditMemo_id})/Microsoft.NAV.post',
                'operation_id': 'post_action_sales_credit_memos',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'required': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'sales_credit_memo_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'sales_credit_memo_id': 'salesCreditMemo_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'sales_credit_memo_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__post_action_sales_credit_memos
        )

        def __post_and_send_action_sales_credit_memos(
            self,
            company_id,
            sales_credit_memo_id,
            **kwargs
        ):
            """Performs the postAndSend action for salesCreditMemos entity  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_and_send_action_sales_credit_memos(company_id, sales_credit_memo_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                sales_credit_memo_id (str): (v1.0) id for salesCreditMemo

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['sales_credit_memo_id'] = \
                sales_credit_memo_id
            return self.call_with_http_info(**kwargs)

        self.post_and_send_action_sales_credit_memos = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos({salesCreditMemo_id})/Microsoft.NAV.postAndSend',
                'operation_id': 'post_and_send_action_sales_credit_memos',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'required': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'sales_credit_memo_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'sales_credit_memo_id': 'salesCreditMemo_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'sales_credit_memo_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__post_and_send_action_sales_credit_memos
        )

        def __post_sales_credit_memo(
            self,
            company_id,
            content_type,
            sales_credit_memo,
            **kwargs
        ):
            """Creates an object of type salesCreditMemo in Dynamics 365 Business Central  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.post_sales_credit_memo(company_id, content_type, sales_credit_memo, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                content_type (str): (v1.0) application/json
                sales_credit_memo (SalesCreditMemo):

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                SalesCreditMemo
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['content_type'] = \
                content_type
            kwargs['sales_credit_memo'] = \
                sales_credit_memo
            return self.call_with_http_info(**kwargs)

        self.post_sales_credit_memo = _Endpoint(
            settings={
                'response_type': (SalesCreditMemo,),
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos',
                'operation_id': 'post_sales_credit_memo',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'content_type',
                    'sales_credit_memo',
                ],
                'required': [
                    'company_id',
                    'content_type',
                    'sales_credit_memo',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'content_type':
                        (str,),
                    'sales_credit_memo':
                        (SalesCreditMemo,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'content_type': 'Content-Type',
                },
                'location_map': {
                    'company_id': 'path',
                    'content_type': 'header',
                    'sales_credit_memo': 'body',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [
                    'application/json'
                ],
                'content_type': [
                    'application/json'
                ]
            },
            api_client=api_client,
            callable=__post_sales_credit_memo
        )

        def __send_action_sales_credit_memos(
            self,
            company_id,
            sales_credit_memo_id,
            **kwargs
        ):
            """Performs the send action for salesCreditMemos entity  # noqa: E501

            This method makes a synchronous HTTP request by default. To make an
            asynchronous HTTP request, please pass async_req=True

            >>> thread = api.send_action_sales_credit_memos(company_id, sales_credit_memo_id, async_req=True)
            >>> result = thread.get()

            Args:
                company_id (str): (v1.0) id for company
                sales_credit_memo_id (str): (v1.0) id for salesCreditMemo

            Keyword Args:
                _return_http_data_only (bool): response data without head status
                    code and headers. Default is True.
                _preload_content (bool): if False, the urllib3.HTTPResponse object
                    will be returned without reading/decoding response data.
                    Default is True.
                _request_timeout (int/float/tuple): timeout setting for this request. If
                    one number provided, it will be total request timeout. It can also
                    be a pair (tuple) of (connection, read) timeouts.
                    Default is None.
                _check_input_type (bool): specifies if type checking
                    should be done one the data sent to the server.
                    Default is True.
                _check_return_type (bool): specifies if type checking
                    should be done one the data received from the server.
                    Default is True.
                _host_index (int/None): specifies the index of the server
                    that we want to use.
                    Default is read from the configuration.
                async_req (bool): execute request asynchronously

            Returns:
                None
                    If the method is called asynchronously, returns the request
                    thread.
            """
            kwargs['async_req'] = kwargs.get(
                'async_req', False
            )
            kwargs['_return_http_data_only'] = kwargs.get(
                '_return_http_data_only', True
            )
            kwargs['_preload_content'] = kwargs.get(
                '_preload_content', True
            )
            kwargs['_request_timeout'] = kwargs.get(
                '_request_timeout', None
            )
            kwargs['_check_input_type'] = kwargs.get(
                '_check_input_type', True
            )
            kwargs['_check_return_type'] = kwargs.get(
                '_check_return_type', True
            )
            kwargs['_host_index'] = kwargs.get('_host_index')
            kwargs['company_id'] = \
                company_id
            kwargs['sales_credit_memo_id'] = \
                sales_credit_memo_id
            return self.call_with_http_info(**kwargs)

        self.send_action_sales_credit_memos = _Endpoint(
            settings={
                'response_type': None,
                'auth': [
                    'oAuth'
                ],
                'endpoint_path': '/companies({company_id})/salesCreditMemos({salesCreditMemo_id})/Microsoft.NAV.send',
                'operation_id': 'send_action_sales_credit_memos',
                'http_method': 'POST',
                'servers': None,
            },
            params_map={
                'all': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'required': [
                    'company_id',
                    'sales_credit_memo_id',
                ],
                'nullable': [
                ],
                'enum': [
                ],
                'validation': [
                ]
            },
            root_map={
                'validations': {
                },
                'allowed_values': {
                },
                'openapi_types': {
                    'company_id':
                        (str,),
                    'sales_credit_memo_id':
                        (str,),
                },
                'attribute_map': {
                    'company_id': 'company_id',
                    'sales_credit_memo_id': 'salesCreditMemo_id',
                },
                'location_map': {
                    'company_id': 'path',
                    'sales_credit_memo_id': 'path',
                },
                'collection_format_map': {
                }
            },
            headers_map={
                'accept': [],
                'content_type': [],
            },
            api_client=api_client,
            callable=__send_action_sales_credit_memos
        )
